version: 2.1

orbs:
  android: circleci/android@2.1.0
  flutter-orb: circleci/flutter@1.1.0
  ruby: circleci/ruby@1.8.0
  macos: circleci/macos@2.2.0

commands:
    accept-licenses:
        description: |
            Accept all Android SDK Manager licenses
        steps:
            - run:
                command: |
                    yes | sdkmanager --licenses
                    yes | sdkmanager --update
                description: |
                    Accepts all Android SDK licenses. This command is typically not necessary to execute, since the CircleCI machine/convenience images ship with all licenses accepted. This command will add approximately 10 seconds to the build time.
                name: Accept Android Licenses
                shell: /bin/bash -e

jobs:
  integration_test_android:
    executor:
      name: android/android-machine
      resource-class: xlarge
      tag: 2022.03.1
    steps:
      - checkout
      - accept-licenses
      - android/create-avd:
          avd-name: myavd
          system-image: system-images;android-30;default;x86
          install: true
      - android/create-avd:
          avd-name: myavd
          system-image: system-images;android-31;default;x86
          install: true
      - flutter-orb/install_sdk_and_pub:
          cache-version: machine
          flutter_version: 3.0.3
      - run: flutter doctor
      - run: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/appk-release.apk


workflows:
  test_and_distribute:
    jobs:
      - integration_test_android
