version: 2.1

orbs:
  android: circleci/android@2.1.0
  flutter-orb: circleci/flutter@1.1.0
  ruby: circleci/ruby@1.8.0
  macos: circleci/macos@2.2.0

jobs:
  integration_test_android:
    executor:
      name: android/android-machine
      resource-class: xlarge
      tag: 2022.03.1
    steps:
      - checkout
      - flutter-orb/install_sdk_and_pub:
          cache-version: machine
          flutter_version: 3.0.3
      - run: flutter doctor
      - run: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/appk-release.apk


workflows:
  test_and_distribute:
    jobs:
      - integration_test_android
